### PR TITLE
Add support for building on Apple Silicon/M1

### PR DESCRIPTION
**Pull request by areese**
Don't #include <malloc.h> if __APPLE__ is defined
Detect posix_memalign in CMake

### CODE REVIEW

**Comment by areese** [comment]
Updated to reflect https://github.com/monkey/monkey/pull/340

**Comment by cosmo0920** [comment]
Hi @edsiper,

Today I got received Apple silicon laptop and, without this patch, I cannot build flb_libco and its users monkey http library and fluent-bit do not build for Apple silicon architecture.

This patch makes sense for me.

**Comment by edsiper** [comment]
my apologies for the delay! thanks so much for this contribution!

**Comment by areese** [comment]
Thank you

**Pull request merged**
